mail:
  username: test@test.test
  password: password

spring:
  application:
    name: estore
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/estore
    username: postgres
    password: password
  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  thymeleaf:
    encoding: UTF-8